source 'https://rubygems.org'


gem 'rails', '4.2.6'

gem 'rails-api'

gem 'spring', :group => :development


gem 'sqlite3'

gem 'oauth'
gem 'jwt'

gem 'rack-cors', :require => 'rack/cors'

gem 'rails_api_auth', :path => "~/oauth/rails_api_auth"
gem 'responders', '~> 2.0'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
